services:
  - type: web
    name: saberes-de-coracao
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: PORT
        value: "3000"
      - key: ADMIN_PASS
        sync: false
