services:
  - type: web
    name: saberes-de-coracao
    env: node
    buildCommand: npm install
    startCommand: node server/app.js
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: ADMIN_PASS
        sync: false
      - key: MIDIA_BASE_URL
        value: https://res.cloudinary.com/deblzssiw
